#    .oooooo.   oooo                      .   ooooo                            oooo
#   d8P'  `Y8b  `888                    .o8   `888'                            `888
#  888           888 .oo.    .oooo.   .o888oo  888          .ooooo.   .ooooo.   888  oooo
#  888           888P"Y88b  `P  )88b    888    888         d88' `88b d88' `"Y8  888 .8P'
#  888           888   888   .oP"888    888    888         888   888 888        888888.
#  `88b    ooo   888   888  d8(  888    888 .  888       o 888   888 888   .o8  888 `88b.
#   `Y8bood8P'  o888o o888o `Y888""8o   "888" o888ooooood8 `Y8bod8P' `Y8bod8P' o888o o888o
#
name: ChatLock
main: com.xardaa49.chatlock.Main
version: 1.0.0
api: [2.0.0]
author: xArdaa49
website: https://github.com/xArdaa49
description: "A plugin that offers the functionality to enable or disable chat for players."

permissions:
  chatlock.use:
    description: Allow to lock or unlock chat
    default: op
  chatlock.bypass:
    description: Permission to send messages while chat is locked
    default: op
